Databases/week2
claudion3/hyf-homework pull request #21
Opened 2020-08-26 19:01 UTC by claudion3

2020-08-27 07:25 UTC, babakbandpey commented on databases/week2/school_database/schoolDB.sql
> +class_id int unsigned not null,
I am sorry for repeating myself, but this class_id is not belong to this table.
Can an student exist without being a part of a class?
Yes the student can exist in the system without being enrolled into any classes.

I believe that I have explained that you need to create a relational model which can accommodate many classes for one student and many students for one class.

2020-08-27 07:27 UTC, babakbandpey requested changes
Hello,
Please create a table which is a relation between the classes and the students.
I have commented on it.
Thanks.

2020-09-02 05:52 UTC, babakbandpey requested changes
Hello again,

You have removed the school schema and most of my comments revolved around perfecting that model. So I do not see why we had these reviews.
Please remove the PDF file and the the school.mwb.bak and I will partially approve your PR.

Thank you.

2020-09-05 10:36 UTC, claudion3 commented
hello Babak, 
you are not clear when you give the reviews i don't know if i'm only one who don't get what you means ex: this what you wrote on previous reviews (Please create a table which is a relation between the classes and the students.) and i did you can also see it on that pdf but i can't upload the data it get encrypted when i upload mwb file. and i was checking what other did to see if i'm missing something and i saw also they added pdf.

so, what exactly you want me to change?

2020-09-29 16:33 UTC, merged